// packages/docs/demos/react/components/Tag/plain.tsx
import { Space, Tag } from '@aurora/horizon-react';

export default function Demo() {
  return (
    <Space wrap>
      <Tag plain>Environment</Tag>
      <Tag plain variant="success">
        Verified
      </Tag>
      <Tag plain variant="warning">
        Review
      </Tag>
      <Tag plain variant="error">
        Blocked
      </Tag>
    </Space>
  );
}

// packages/doc/docs/components/Tag/demos/plain.vue
<template>
  <n-tag :clickable="false" :plain="true">Default</n-tag>
  <n-tag :clickable="false" :plain="true" type="success">Success</n-tag>
  <n-tag :clickable="false" :plain="true" type="info">Info</n-tag>
  <n-tag :clickable="false" :plain="true" type="warning">Warning</n-tag>
  <n-tag :clickable="false" :plain="true" type="error">Error</n-tag>
</template>

<script setup lang="ts">
</script>

<style scoped>
</style>
