// packages/locale-react/src/components/NumberLocale.ts
import type { HTMLAttributes, ReactElement } from 'react';
import { createElement } from 'react';
import type { LocaleNumberFormatterOptions } from '@aurora/locale';
import { useLocale } from '../context';
import { mergeClassName } from './utils';

export interface NumberLocaleProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  value: number | string;
  option?: LocaleNumberFormatterOptions;
}

export function NumberLocale({
  value,
  option,
  className,
  ...props
}: NumberLocaleProps): ReactElement {
  const locale = useLocale();
  return createElement(
    'span',
    { ...props, className: mergeClassName('horizon-web-number-locale', className) },
    locale.numberService.n(Number(value), option),
  );
}

// packages/locale-vue/src/components/NumberLocale.tsx
import type { PropType } from 'vue';
import { defineComponent, getCurrentInstance } from 'vue';
import type { LocaleNumberFormatterOptions } from '@aurora/locale';
import { useNamespace } from '@aurora/utils';

export default defineComponent({
  name: `${useNamespace()}NumberLocale`,
  props: {
    value: {
      type: [Number, String],
      required: true,
    },
    option: {
      type: Object as PropType<LocaleNumberFormatterOptions>,
    },
  },
  setup(props) {
    const { proxy } = getCurrentInstance()!;
    return () => (
      <div class="horizon-web-number-locale">{proxy!.$root?.n(Number(props.value), props.option)}</div>
    );
  },
});
