// packages/horizon-web-react/src/components/Link/index.tsx
import type {
  AnchorHTMLAttributes,
  ForwardedRef,
  KeyboardEvent,
  MouseEvent,
  ReactElement,
  ReactNode,
} from 'react';
import { forwardRef, useEffect, useMemo } from 'react';
import type {
  AdaptComponentApiShape,
  ComponentEventHandlers,
  LinkCommonProps,
  LinkEventMap,
  LinkRegionMap,
} from '@aurora/core';
import {
  getLinkLoadingIconSize,
  isLinkActionRole,
  LINK_DEFAULTS,
  resolveLinkAction,
} from '@aurora/core';
import type { LinkScrollTarget } from '@aurora/horizon-web-core';
import { scrollLinkAnchor } from '@aurora/horizon-web-core';
import { cls, ComponentClassBlock } from '@aurora/theme';
import { useHorizonWebConfig } from '../../provider';
import { LoadingIcon } from '../_shared/LoadingIcon';

type LinkReactEventMap = AdaptComponentApiShape<
  LinkEventMap<MouseEvent<HTMLElement>>,
  {
    click: 'onClick';
  }
>;

type LinkReactCallbacks = ComponentEventHandlers<LinkReactEventMap>;

type LinkReactRegions = AdaptComponentApiShape<
  { [Name in keyof LinkRegionMap]?: ReactNode },
  { content: 'children' }
>;

type LinkReactCommonProps = AdaptComponentApiShape<LinkCommonProps, { route: 'to' }>;

export type LinkProps = LinkReactCommonProps &
  LinkReactCallbacks &
  LinkReactRegions &
  Omit<
    AnchorHTMLAttributes<HTMLAnchorElement>,
    'children' | 'href' | 'onClick' | 'prefix' | 'size' | 'suffix' | 'target' | 'type'
  > & {
    /** 前缀图标或内容。@en Leading icon or content. */
    icon?: ReactNode;
    /** 图标尺寸。@en Icon size. */
    iconSize?: string | number;
    /** 锚点滚动容器或选择器。@en Anchor scroll container or selector. */
    scrollTarget?: LinkScrollTarget;
  };

export const Link = forwardRef<HTMLAnchorElement | HTMLSpanElement, LinkProps>(function Link(
  {
    variant = LINK_DEFAULTS.variant,
    size = LINK_DEFAULTS.size,
    underline = LINK_DEFAULTS.underline,
    disabled = LINK_DEFAULTS.disabled,
    href,
    target,
    attribute = LINK_DEFAULTS.attribute,
    anchor,
    anchorPosition = LINK_DEFAULTS.anchorPosition,
    anchorOffset = LINK_DEFAULTS.anchorOffset,
    to,
    replace = LINK_DEFAULTS.replace,
    loading = LINK_DEFAULTS.loading,
    prefix,
    suffix,
    icon,
    iconSize,
    scrollTarget = 'body',
    children,
    onClick,
    onKeyDown,
    className,
    ...nativeProps
  },
  ref,
): ReactElement {
  const config = useHorizonWebConfig();
  const classes = useMemo(
    () => new ComponentClassBlock('link', config.namespace.toLowerCase()),
    [config.namespace],
  );
  const routeHref = to === undefined ? undefined : config.resolveHref?.(to);
  const resolvedHref = to === undefined ? href : (routeHref ?? href);
  const actionRole = isLinkActionRole(anchor, resolvedHref);
  const inactive = disabled || loading;

  function scrollToCurrent(link: Element): void {
    const scrolled = scrollLinkAnchor({
      anchor: anchor ?? '',
      link,
      target: scrollTarget,
      offset: anchorOffset,
    });
    if (!scrolled) console.warn('Cannot find scroll-target');
  }

  useEffect(() => {
    if (!anchor || typeof window === 'undefined') return;
    if (window.location.hash.replace(/^#/, '') !== anchor) return;
    const link = document.getElementById(anchor);
    if (link) scrollToCurrent(link);
  }, [anchor]);

  function handleClick(event: MouseEvent<HTMLElement>): void {
    const action = resolveLinkAction({
      disabled,
      loading,
      anchor,
      route: to,
      canNavigateRoute: Boolean(config.navigate),
      href: resolvedHref,
    });

    if (action === 'blocked' || action === 'anchor') {
      event.preventDefault();
      return;
    }
    if (action === 'route') {
      event.preventDefault();
      void config.navigate?.(to, { replace });
      return;
    }
    onClick?.(event);
  }

  function handleAnchorClick(event: MouseEvent<HTMLAnchorElement>): void {
    event.stopPropagation();
    event.preventDefault();
    if (inactive || !anchor) return;
    const link = event.currentTarget.parentElement;
    if (link) scrollToCurrent(link);
  }

  function handleKeyDown(event: KeyboardEvent<HTMLAnchorElement>): void {
    onKeyDown?.(event);
    if (event.defaultPrevented || !actionRole || inactive) return;
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      event.currentTarget.click();
    }
  }

  const rootClassName = cls(
    classes.block,
    classes.m(variant),
    classes.m(size),
    classes.is('disabled', disabled),
    classes.has('underline', Boolean(underline)),
    classes.is('underline-always', underline === 'always'),
    classes.has('attribute', attribute),
    classes.has('anchor', Boolean(anchor)),
    classes.is('anchor-left', anchorPosition === 'left'),
    className,
  );
  const content = loading ? (
    <>
      <LoadingIcon
        className={classes.e('loading-icon')}
        namespace={config.namespace}
        size={getLinkLoadingIconSize(size)}
      />
      <span className={classes.e('inner')}>{config.linkLabels.loading}</span>
    </>
  ) : (
    <>
      {prefix !== undefined && <span className={classes.e('prefix')}>{prefix}</span>}
      <span className={classes.e('inner')}>{children}</span>
      {suffix !== undefined && <span className={classes.e('suffix')}>{suffix}</span>}
      {icon !== undefined && (
        <span className={classes.e('suffix')} style={{ fontSize: iconSize }}>
          {icon}
        </span>
      )}
      {anchor && (
        <a
          aria-disabled={inactive || undefined}
          className={classes.e('anchor')}
          href={`#${anchor}`}
          onClick={handleAnchorClick}
          tabIndex={inactive ? -1 : undefined}
          target={target}
        >
          #
        </a>
      )}
    </>
  );

  if (anchor) {
    return (
      <span
        {...nativeProps}
        aria-busy={loading || undefined}
        aria-disabled={inactive || undefined}
        className={rootClassName}
        id={anchor}
        ref={ref as ForwardedRef<HTMLSpanElement>}
      >
        {content}
      </span>
    );
  }

  return (
    <a
      {...nativeProps}
      aria-busy={loading || undefined}
      aria-disabled={inactive || undefined}
      className={rootClassName}
      href={inactive ? undefined : resolvedHref}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      ref={ref as ForwardedRef<HTMLAnchorElement>}
      role={actionRole ? 'button' : undefined}
      tabIndex={inactive ? -1 : actionRole ? 0 : nativeProps.tabIndex}
      target={target}
    >
      {content}
    </a>
  );
});

export const HLink = Link;

// packages/horizon-web-vue/src/components/Link/src/Link.tsx
import type { ComputedRef } from 'vue';
import {
  computed,
  defineComponent,
  getCurrentInstance,
  inject,
  nextTick,
  onMounted,
  ref,
} from 'vue';
import { useLinkProps } from './composables/useProps';
import type { Router } from 'vue-router';
import type { HorizonWebSetupContext } from '@aurora/utils';
import { cls, ComponentClassBlock, HChildOnly, useNamespace } from '@aurora/utils';
import { getLinkLoadingIconSize, isLinkActionRole, resolveLinkAction } from '@aurora/core';
import { scrollLinkAnchor } from '@aurora/horizon-web-core';
import type { LinkEmits } from './composables/useEmits';
import { useLinkEmits } from './composables/useEmits';
import type { LinkSlots } from './composables/useSlots';
import { useLinkSlots } from './composables/useSlots';
import { GlobalSizeInjectedKey } from '~/components/Application/src/utils/injectedKeys';
import type { HApplicationSizeType } from '~/components/Application/src/composables/useProps';
import { defaultLocale, localeInjectKey } from '~/provides';
import { renderIcon } from '~/utils/useIcon';
import LoadingIcon from '~/directives/v-loading/src/components/LoadingIcon';

export default defineComponent({
  name: `${useNamespace()}Link`,
  desc: '文字超链接',
  descLocales: { en: 'Basic text link usage' },
  props: useLinkProps,
  emits: useLinkEmits,
  slots: useLinkSlots,
  setup(props, { slots, emit }: HorizonWebSetupContext<LinkEmits, LinkSlots>) {
    const classHelper = new ComponentClassBlock('link');
    const instance = getCurrentInstance();
    const router = instance?.appContext.config.globalProperties.$router as Router | undefined;
    const redirectHref = computed(() => {
      if (props.to) {
        if (!router) {
          console.warn(
            `You haven't import "vue-router". The props of 'to' and 'replace' will be ignored.`,
          );
          return props.href;
        } else {
          return router.resolve(props.to).href;
        }
      }
      return props.href;
    });

    // global size
    const globalSize = inject(GlobalSizeInjectedKey, ref('medium'));
    const sizeRef = computed(
      () => props.size || globalSize.value,
    ) as ComputedRef<HApplicationSizeType>;

    // locale
    const locale = inject(localeInjectKey, defaultLocale);

    const onClick = (evt: MouseEvent): void => {
      const action = resolveLinkAction({
        disabled: props.disabled,
        loading: props.loading,
        anchor: props.anchor,
        route: props.to,
        canNavigateRoute: Boolean(router),
        href: redirectHref.value,
      });

      if (action === 'anchor' || action === 'blocked') {
        evt.preventDefault();
        return;
      }

      if (action === 'route' && props.to && router) {
        evt.preventDefault();
        props.replace ? router.replace(props.to) : router.push(props.to);
        return;
      }

      emit('click', evt);
    };

    const onClickAnchor = (evt: MouseEvent): void => {
      if (props.anchor) {
        evt.stopPropagation();
        evt.preventDefault();
        if (props.disabled || props.loading) return;
        scrollToCurrent();
      }
    };

    const scrollToCurrent = (): void => {
      nextTick(() => {
        const link = instance?.proxy?.$el;
        if (
          !(link instanceof Element) ||
          !scrollLinkAnchor({
            anchor: props.anchor || '',
            link,
            target: props.scrollTarget,
            offset: props.anchorOffset,
          })
        ) {
          console.warn('Cannot find scroll-target');
        }
      });
    };

    onMounted(() => {
      if (props.anchor) {
        const hash = window.location.hash.replace(/^#/, '');
        if (hash === props.anchor) {
          scrollToCurrent();
        }
      }
    });

    const contentRender = () => (
      <HChildOnly>
        {slots.prefix ? <span class={classHelper.e('prefix')}>{slots.prefix?.()}</span> : ''}
        <span class={classHelper.e('inner')}>{slots.default?.()}</span>
        {slots.suffix ? <span class={classHelper.e('suffix')}>{slots.suffix?.()}</span> : ''}
        {props.icon ? (
          <span class={classHelper.e('suffix')}>
            {renderIcon(props.icon, undefined, { size: props.iconSize })}
          </span>
        ) : (
          ''
        )}
        {!!props.anchor && (
          <a
            class={classHelper.e('anchor')}
            href={`#${props.anchor}`}
            target={props.target}
            onClick={onClickAnchor}
          >
            #
          </a>
        )}
      </HChildOnly>
    );

    const wrapperElement = computed(() => (props.anchor ? 'span' : 'a'));
    const isAction = computed(() => isLinkActionRole(props.anchor, redirectHref.value));

    const onActionKeydown = (evt: KeyboardEvent) => {
      if (!isAction.value || props.disabled || props.loading) return;

      if (evt.key === 'Enter' || evt.key === ' ') {
        evt.preventDefault();
        (evt.currentTarget as HTMLElement).click();
      }
    };

    return () => (
      <wrapperElement.value
        class={cls(
          classHelper.block,
          classHelper.m(props.type),
          classHelper.m(sizeRef.value),
          classHelper.is('disabled', props.disabled),
          classHelper.has('underline', !!props.underline),
          classHelper.is('underline-always', props.underline === 'always'),
          classHelper.has('attribute', props.attribute),
          classHelper.has('anchor', !!props.anchor),
          classHelper.is('anchor-left', props.anchorPosition === 'left'),
        )}
        href={props.disabled ? undefined : redirectHref.value}
        target={props.target}
        role={isAction.value ? 'button' : undefined}
        tabindex={isAction.value && !props.disabled && !props.loading ? 0 : undefined}
        aria-disabled={isAction.value && (props.disabled || props.loading) ? true : undefined}
        onClick={onClick}
        onKeydown={onActionKeydown}
      >
        {props.loading ? (
          <HChildOnly>
            <LoadingIcon
              class={classHelper.e('loading-icon')}
              style={{
                width: `${getLinkLoadingIconSize(sizeRef.value)}px`,
                height: `${getLinkLoadingIconSize(sizeRef.value)}px`,
              }}
            />
            <span class={classHelper.e('inner')}>
              {locale.value?.langService.td().horizonWeb.link.loading}
            </span>
          </HChildOnly>
        ) : (
          contentRender()
        )}
      </wrapperElement.value>
    );
  },
});
