// packages/docs/demos/vue/components/Panels/vertical.vue
<template>
  <div class="docs-demo">
    <h-radio-group v-model="currentPanel">
      <h-radio value="draft">Draft</h-radio>
      <h-radio value="review">Review</h-radio>
      <h-radio value="approved">Approved</h-radio>
    </h-radio-group>
    <h-panels v-model="currentPanel" vertical animated>
      <h-panel v-for="panel in panels" :key="panel.name" :name="panel.name">
        <p class="panel-content">{{ panel.content }}</p>
      </h-panel>
    </h-panels>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const currentPanel = ref('draft');
const panels = [
  { name: 'draft', content: 'Shape the proposal.' },
  { name: 'review', content: 'Collect team feedback.' },
  { name: 'approved', content: 'Prepare the rollout.' },
];
</script>

<style scoped>
.panel-content {
  margin: 0;
  padding: var(--h-spacing-5);
  color: var(--h-text-secondary);
}
</style>

// packages/docs/demos/react/components/Panels/vertical.tsx
import { useState } from 'react';
import { Panel, Panels, Segmented, SegmentedItem } from '@aurora/horizon-react';

export default function PanelsVerticalDemo({ locale }: { locale: 'en' | 'zh' }) {
  const en = locale === 'en';
  const [value, setValue] = useState('draft');

  return (
    <section className="docs-demo">
      <Segmented onChange={next => setValue(String(next))} value={value}>
        <SegmentedItem value="draft">{en ? 'Draft' : '草稿'}</SegmentedItem>
        <SegmentedItem value="review">{en ? 'Review' : '评审'}</SegmentedItem>
        <SegmentedItem value="approved">{en ? 'Approved' : '已通过'}</SegmentedItem>
      </Segmented>
      <Panels animated vertical value={value}>
        <Panel name="draft">{en ? 'Shape the proposal.' : '完善方案内容。'}</Panel>
        <Panel name="review">{en ? 'Collect team feedback.' : '收集团队反馈。'}</Panel>
        <Panel name="approved">{en ? 'Prepare the rollout.' : '准备发布计划。'}</Panel>
      </Panels>
    </section>
  );
}
