// packages/docs/demos/vue/components/Tabs/editable.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { HTabValue } from '@aurora/horizon-web-vue';

interface DocumentTab {
  key: string;
  label: string;
  closable: boolean;
}

const activeKey = ref('overview');
const counter = ref(2);
const status = ref('Use + to add a tab or close an editable tab.');
const documents = ref<DocumentTab[]>([
  { key: 'overview', label: 'Overview', closable: false },
  { key: 'brief-1', label: 'Research brief', closable: true },
  { key: 'brief-2', label: 'Launch notes', closable: true },
]);

function addDocument() {
  counter.value += 1;
  const document = {
    key: `brief-${counter.value}`,
    label: `Untitled ${counter.value}`,
    closable: true,
  };
  documents.value = [...documents.value, document];
  activeKey.value = document.key;
  status.value = `${document.label} added.`;
}

function closeDocument(key: HTabValue) {
  const target = documents.value.find(document => document.key === key);
  documents.value = documents.value.filter(document => document.key !== key);
  if (activeKey.value === key) activeKey.value = documents.value[0]?.key ?? '';
  status.value = `${target?.label ?? String(key)} closed.`;
}
</script>

<template>
  <div class="tabs-editable-demo">
    <h-tabs
      v-model:active-key="activeKey"
      editable
      type="card"
      @add="addDocument"
      @close="closeDocument"
    >
      <h-tab
        v-for="document in documents"
        :key="document.key"
        :label="document.label"
        :closable="document.closable"
      />
    </h-tabs>
    <p aria-live="polite">{{ status }}</p>
  </div>
</template>

<style scoped>
.tabs-editable-demo {
  display: grid;
  min-width: 0;
  gap: var(--h-spacing-4);
}

.tabs-editable-demo p {
  margin: 0;
  color: var(--h-text-secondary);
  font-size: var(--h-text-sm);
}
</style>

// packages/docs/demos/react/components/Tabs/editable.tsx
import { useState } from 'react';
import type { TabsKey } from '@aurora/horizon-web-react';
import { Tab, Tabs } from '@aurora/horizon-web-react';

interface DocumentTab {
  key: string;
  label: string;
  closable: boolean;
}

export default function TabsEditableDemo({ locale }: { locale: 'en' | 'zh' }) {
  const en = locale === 'en';
  const [activeKey, setActiveKey] = useState<TabsKey>('overview');
  const [counter, setCounter] = useState(2);
  const [documents, setDocuments] = useState<DocumentTab[]>([
    { key: 'overview', label: en ? 'Overview' : '概览', closable: false },
    { key: 'brief-1', label: en ? 'Research brief' : '研究简报', closable: true },
    { key: 'brief-2', label: en ? 'Launch notes' : '发布记录', closable: true },
  ]);

  function addDocument() {
    const next = counter + 1;
    const document = {
      key: `brief-${next}`,
      label: en ? `Untitled ${next}` : `未命名 ${next}`,
      closable: true,
    };
    setCounter(next);
    setDocuments(current => [...current, document]);
    setActiveKey(document.key);
  }

  function closeDocument(key: TabsKey | undefined) {
    if (key === undefined) return;
    setDocuments(current => current.filter(document => document.key !== key));
  }

  return (
    <section className="docs-demo">
      <Tabs
        draggable
        editable
        onAdd={addDocument}
        onChange={setActiveKey}
        onClose={closeDocument}
        value={activeKey}
        variant="card"
      >
        {documents.map(document => (
          <Tab
            closable={document.closable}
            key={document.key}
            label={document.label}
            value={document.key}
          />
        ))}
      </Tabs>
      <span aria-live="polite" className="docs-demo__status">
        {en ? `${documents.length} documents` : `${documents.length} 个文档`}
      </span>
    </section>
  );
}
