// packages/docs/demos/components/Button/size.vue
<script setup lang="ts"></script>

<template>
  <n-row>
    <n-col :span="24">
      <n-button size="small" :auto-fit="true">Small</n-button>
      <n-button size="medium" :auto-fit="true">Medium</n-button>
      <n-button size="large" :auto-fit="true">Large</n-button>
    </n-col>
  </n-row>
</template>

<style scoped>
.n-button + .n-button {
  margin-left: 10px;
}
</style>

// packages/docs/demos/react/components/Button/size.tsx
import { Button } from '@aurora/horizon-react';

export default function ButtonSizeDemo({ locale }: { locale: 'en' | 'zh' }) {
  const label = locale === 'en' ? 'Create' : '创建';
  return (
    <div className="docs-demo__actions">
      <Button size="huge">{label}</Button>
      <Button size="large">{label}</Button>
      <Button size="medium">{label}</Button>
      <Button size="small">{label}</Button>
      <Button autoFit>{locale === 'en' ? 'Fit' : '适应内容'}</Button>
    </div>
  );
}
