// packages/horizon-web-react/src/components/Anchor/index.tsx
import type {
  CSSProperties,
  ForwardRefExoticComponent,
  HTMLAttributes,
  MouseEvent,
  ReactElement,
  ReactNode,
  RefAttributes,
} from 'react';
import {
  Children,
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';
import type {
  AnchorCommonProps,
  AnchorLinkCommonProps,
  AnchorLinkInfo,
  AnchorListItem,
  AnchorOffset,
} from '@aurora/core';
import { ANCHOR_DEFAULTS, ANCHOR_LINK_DEFAULTS, resolveActiveAnchorLink } from '@aurora/core';
import type { AnchorScrollController, AnchorScrollTarget } from '@aurora/horizon-web-core';
import {
  createAnchorScrollController,
  getAnchorCustomOffset,
  getAnchorOffsetTop,
  getAnchorScrollTop,
  resolveAnchorHashTarget,
  resolveAnchorScrollTarget,
  scanAnchorHeadings,
} from '@aurora/horizon-web-core';
import { cls, ComponentClassBlock } from '@aurora/theme';
import { useHorizonWebConfig } from '../../provider';

export type ReactAnchorScrollTarget = AnchorScrollTarget | (() => AnchorScrollTarget);
type SharedAnchorProps = AnchorCommonProps<ReactAnchorScrollTarget, ReactNode>;

export interface AnchorProps
  extends
    Omit<SharedAnchorProps, 'collapsed'>,
    Omit<HTMLAttributes<HTMLElement>, 'children' | 'onChange' | 'onClick' | 'style'> {
  /** 导航链接。 @en Navigation links. */
  children?: ReactNode;
  /** 受控折叠状态。 @en Controlled collapsed state. */
  collapsed?: boolean;
  /** 根元素样式。 @en Root element style. */
  style?: CSSProperties;
  /** 点击章节链接。 @en Called when a section link is clicked. */
  onLinkClick?: (link: AnchorLinkInfo, event: MouseEvent<HTMLAnchorElement>) => void;
  /** 活动章节变化。 @en Called when the active section changes. */
  onChange?: (link: string, previousLink: string) => void;
  /** 折叠状态变化。 @en Called when the collapsed state changes. */
  onCollapseChange?: (collapsed: boolean) => void;
}

export interface AnchorLinkProps extends AnchorLinkCommonProps {
  /** 子级链接。 @en Nested links. */
  children?: ReactNode;
  /** 自定义标题。 @en Custom title content. */
  titleContent?: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export interface AnchorHandle {
  updateActiveLink(link: string, scroll?: boolean): void;
  refreshAnchorList(): void;
  updateScrollContainer(): void;
  getAnchorList(): AnchorListItem[];
  readonly element: HTMLElement | null;
}

interface AnchorContextValue {
  activeLink: string;
  changeHash: boolean;
  linkTarget?: AnchorLinkProps['target'];
  showTitleSuffix: boolean;
  register(link: string): () => void;
  activate(link: AnchorLinkInfo, event: MouseEvent<HTMLAnchorElement>): void;
}

const AnchorContext = createContext<AnchorContextValue | null>(null);
const AnchorDepthContext = createContext(0);

function resolveTargetValue(target: ReactAnchorScrollTarget | undefined): AnchorScrollTarget {
  return typeof target === 'function' ? target() : target;
}

export const AnchorLink = forwardRef<HTMLDivElement, AnchorLinkProps>(function AnchorLink(
  { title, href, target = ANCHOR_LINK_DEFAULTS.target, children, titleContent, className, style },
  ref,
): ReactElement {
  const config = useHorizonWebConfig();
  const context = useContext(AnchorContext);
  const depth = useContext(AnchorDepthContext);
  const classes = useMemo(
    () => new ComponentClassBlock('anchor', config.namespace.toLowerCase()),
    [config.namespace],
  );
  const childCount = Children.count(children);

  useEffect(() => (href && context ? context.register(href) : undefined), [context, href]);

  const content = title !== undefined ? title : titleContent;
  const suffix =
    context?.showTitleSuffix && depth === 0 && childCount > 0 ? `（${childCount}）` : '';
  return (
    <div className={cls(classes.e('link'), className)} ref={ref} style={style}>
      <div
        className={cls(
          classes.e('link-title'),
          classes.is('active', context?.activeLink === href),
          classes.is('hide', href === undefined && content === undefined),
        )}
      >
        <a
          className={classes.e('link-title-txt')}
          href={href}
          target={context?.linkTarget ?? target}
          title={title}
          onClick={event => {
            if (!href || !context) return;
            if (!context.changeHash) event.preventDefault();
            context.activate({ href, title: title ?? '' }, event);
          }}
        >
          {content}
          {suffix}
        </a>
      </div>
      <AnchorDepthContext.Provider value={depth + 1}>{children}</AnchorDepthContext.Provider>
    </div>
  );
});

function renderAnchorList(items: readonly AnchorListItem[]): ReactNode {
  return items.map((item, index) => (
    <AnchorLink
      href={item.id ? `#${item.id}` : undefined}
      key={`${item.id ?? 'level'}-${index}`}
      title={item.title}
    >
      {item.children ? renderAnchorList(item.children) : null}
    </AnchorLink>
  ));
}

const AnchorImplementation = forwardRef<AnchorHandle, AnchorProps>(function Anchor(
  {
    size = ANCHOR_DEFAULTS.size,
    maxHeight = ANCHOR_DEFAULTS.maxHeight,
    changeHash = ANCHOR_DEFAULTS.changeHash,
    scrollContainer,
    scrollBehavior = ANCHOR_DEFAULTS.scrollBehavior,
    scrollOffset = ANCHOR_DEFAULTS.scrollOffset,
    boundsOffset = ANCHOR_DEFAULTS.boundsOffset,
    useCollapse = ANCHOR_DEFAULTS.useCollapse,
    collapsed,
    defaultCollapsed = ANCHOR_DEFAULTS.defaultCollapsed,
    collapseText = 'Navigation',
    showLine = ANCHOR_DEFAULTS.showLine,
    showHighlightLine = ANCHOR_DEFAULTS.showHighlightLine,
    showTitleSuffix = ANCHOR_DEFAULTS.showTitleSuffix,
    autoRender = ANCHOR_DEFAULTS.autoRender,
    autoRenderRules = ANCHOR_DEFAULTS.autoRenderRules,
    linkTarget,
    children,
    onLinkClick,
    onChange,
    onCollapseChange,
    className,
    style,
    'aria-label': ariaLabel = 'Page sections',
    ...nativeProps
  },
  forwardedRef,
): ReactElement {
  const config = useHorizonWebConfig();
  const classes = useMemo(
    () => new ComponentClassBlock('anchor', config.namespace.toLowerCase()),
    [config.namespace],
  );
  const rootRef = useRef<HTMLElement>(null);
  const targetRef = useRef<HTMLElement | Window | null>(null);
  const scrollControllerRef = useRef<AnchorScrollController | undefined>(undefined);
  const linksRef = useRef<string[]>([]);
  const [activeLink, setActiveLink] = useState('');
  const activeLinkRef = useRef(activeLink);
  const [internalCollapsed, setInternalCollapsed] = useState(defaultCollapsed);
  const [items, setItems] = useState<AnchorListItem[]>([]);
  const [highlightStyle, setHighlightStyle] = useState<CSSProperties>({ top: 0, height: 0 });
  const isScrollingRef = useRef(false);
  const currentCollapsed = collapsed ?? internalCollapsed;
  activeLinkRef.current = activeLink;

  const refreshHighlight = useCallback((link: string) => {
    const root = rootRef.current;
    const anchor = link
      ? Array.from(root?.querySelectorAll<HTMLAnchorElement>('a') ?? []).find(
          element => element.getAttribute('href') === link,
        )
      : undefined;
    const title = anchor?.parentElement;
    setHighlightStyle(
      title ? { top: title.offsetTop, height: title.clientHeight } : { top: 0, height: 0 },
    );
  }, []);

  const scrollToLink = useCallback(
    (link: string) => {
      const target = targetRef.current;
      const document = rootRef.current?.ownerDocument;
      const section = target && document ? resolveAnchorHashTarget(link, document) : null;
      if (!target || !section) return;
      const top =
        getAnchorOffsetTop(section, target) +
        getAnchorScrollTop(target) -
        getAnchorCustomOffset(scrollOffset as AnchorOffset, section, target);
      isScrollingRef.current = true;
      scrollControllerRef.current?.scrollTo(top, scrollBehavior, () => {
        isScrollingRef.current = false;
      });
    },
    [scrollBehavior, scrollOffset],
  );

  const updateActiveLink = useCallback(
    (link: string, scroll = true) => {
      const previous = activeLinkRef.current;
      activeLinkRef.current = link;
      setActiveLink(link);
      if (previous !== link) onChange?.(link, previous);
      refreshHighlight(link);
      if (scroll) scrollToLink(link);
    },
    [onChange, refreshHighlight, scrollToLink],
  );

  const updateScrollContainer = useCallback(() => {
    const document = rootRef.current?.ownerDocument;
    if (!document) return;
    targetRef.current = resolveAnchorScrollTarget(
      resolveTargetValue(scrollContainer),
      document,
      selector => {
        console.warn(
          `[Horizon Web] Anchor scroll container "${selector}" was not found; using window instead.`,
        );
      },
    );
  }, [scrollContainer]);

  const refreshAnchorList = useCallback(() => {
    const target = targetRef.current;
    const root =
      target && !('window' in target) ? target : rootRef.current?.ownerDocument.documentElement;
    if (root) setItems(scanAnchorHeadings(root, autoRenderRules));
  }, [autoRenderRules]);

  useEffect(() => {
    updateScrollContainer();
    const target = targetRef.current;
    if (!target) return;
    scrollControllerRef.current = createAnchorScrollController(target);
    const handleScroll = () => {
      if (isScrollingRef.current) return;
      const document = rootRef.current?.ownerDocument;
      if (!document) return;
      const sections = linksRef.current.flatMap(link => {
        const element = resolveAnchorHashTarget(link, document);
        return element ? [{ link, top: getAnchorOffsetTop(element, target) }] : [];
      });
      const first = linksRef.current[0]
        ? resolveAnchorHashTarget(linksRef.current[0], document)
        : null;
      const boundary = first
        ? getAnchorCustomOffset(boundsOffset as AnchorOffset, first, target)
        : typeof boundsOffset === 'number'
          ? boundsOffset
          : 0;
      updateActiveLink(resolveActiveAnchorLink(sections, boundary), false);
    };
    target.addEventListener('scroll', handleScroll, { passive: true });
    if (autoRender) refreshAnchorList();
    if (globalThis.location?.hash) updateActiveLink(decodeURI(globalThis.location.hash), false);
    return () => {
      target.removeEventListener('scroll', handleScroll);
      scrollControllerRef.current?.destroy();
    };
  }, [autoRender, boundsOffset, refreshAnchorList, updateActiveLink, updateScrollContainer]);

  useEffect(
    () => refreshHighlight(activeLink),
    [activeLink, refreshHighlight, size, showTitleSuffix],
  );

  useImperativeHandle(
    forwardedRef,
    () => ({
      updateActiveLink,
      refreshAnchorList,
      updateScrollContainer,
      getAnchorList: () => items,
      get element() {
        return rootRef.current;
      },
    }),
    [items, refreshAnchorList, updateActiveLink, updateScrollContainer],
  );

  const context = useMemo<AnchorContextValue>(
    () => ({
      activeLink,
      changeHash,
      linkTarget,
      showTitleSuffix,
      register(link) {
        if (!link.startsWith('#')) return () => undefined;
        if (!linksRef.current.includes(link)) linksRef.current = [...linksRef.current, link];
        return () => (linksRef.current = linksRef.current.filter(current => current !== link));
      },
      activate(link, event) {
        onLinkClick?.(link, event);
        updateActiveLink(link.href);
      },
    }),
    [activeLink, changeHash, linkTarget, onLinkClick, showTitleSuffix, updateActiveLink],
  );

  const toggleCollapsed = () => {
    const next = !currentCollapsed;
    if (collapsed === undefined) setInternalCollapsed(next);
    onCollapseChange?.(next);
  };

  return (
    <nav
      {...nativeProps}
      aria-label={ariaLabel}
      className={cls(classes.block, classes.m(size), className)}
      ref={rootRef}
      style={{ ...style, maxHeight }}
    >
      {useCollapse && (
        <button
          aria-expanded={!currentCollapsed}
          className={cls(classes.e('collapse-btn'), classes.is('collapse', currentCollapsed))}
          onClick={toggleCollapsed}
          type="button"
        >
          <span aria-hidden="true">{currentCollapsed ? '›' : '‹'}</span>
          <span className={classes.e('collapse-btn-txt')}>{collapseText}</span>
        </button>
      )}
      <div style={{ maxHeight, overflow: 'auto' }}>
        <div className={classes.e('wrap')} hidden={useCollapse && currentCollapsed}>
          <div className={classes.e('line')} hidden={!showLine}>
            <div
              className={classes.e('line--highlight')}
              hidden={!showHighlightLine}
              style={highlightStyle}
            />
          </div>
          <AnchorContext.Provider value={context}>
            <AnchorDepthContext.Provider value={0}>
              {autoRender ? renderAnchorList(items) : children}
            </AnchorDepthContext.Provider>
          </AnchorContext.Provider>
        </div>
      </div>
    </nav>
  );
});

export const Anchor = AnchorImplementation as ForwardRefExoticComponent<
  AnchorProps & RefAttributes<AnchorHandle>
>;

Anchor.displayName = 'Anchor';

// packages/horizon-vue/src/components/Anchor/src/Anchor.tsx
import {
  computed,
  defineComponent,
  nextTick,
  onBeforeUnmount,
  onMounted,
  provide,
  ref,
  toRefs,
  watch,
} from 'vue';
import type { Ref, CSSProperties, ComputedRef } from 'vue';
import type { AnchorListItem } from '@aurora/core';
import { resolveActiveAnchorLink } from '@aurora/core';
import type { AnchorScrollController } from '@aurora/horizon-core';
import {
  createAnchorScrollController,
  getAnchorCustomOffset,
  getAnchorOffsetTop,
  getAnchorScrollTop,
  resolveAnchorHashTarget,
  resolveAnchorScrollTarget,
  scanAnchorHeadings,
} from '@aurora/horizon-core';
import type { AnchorProps } from './composables/useProps';
import { useAnchorProps } from './composables/useProps';
import { useAnchorEmits } from './composables/useEmits';
import type { AnchorSlots } from './composables/useSlots';
import { useAnchorSlots } from './composables/useSlots';
import type { AnchorEmits } from './composables/useEmits';
import type { HorizonWebSetupContext } from '@aurora/utils';
import { cls, ComponentClassBlock, useNamespace } from '@aurora/utils';
import AnchorLink from './AnchorLink';
import HScrollbar from '~/components/Scrollbar/src/Scrollbar';
import HTooltip from '~/components/Tooltip/src/Tooltip';
import type { AnchorExposes } from './composables/useExposes';
import { useAnchorExposes } from './composables/useExposes';
import useSize from '~/utils/useSize';
import { AnchorContextInjectedKey, AnchorPropsInjectedKey } from './utils/InjectedKeys';
import { AIcon } from '@aurora/icon';
import useLocaleLang from '~/utils/useLocaleLang';

export interface AnchorContext {
  sharedProps: ComputedRef<Pick<AnchorProps, 'size' | 'showTitleSuffix' | 'placement'>>;
  activeLink: Ref<string>;
  addLink: (link: string) => void;
  removeLink: (link: string) => void;
  clickLinkHandle: (linkInfo: { href: string; title: string }, e: MouseEvent) => void;
  updateHighlightLine: (link: string) => void;
}
const sharpLinkRegx = /#([\S ]+)$/;

const highLightLineDefaultStyle = {
  top: '0px',
  height: '0px',
};

export default defineComponent({
  name: `${useNamespace()}Anchor`,
  desc: '电梯导航用来展示当前页面中，有哪些具体内容，并可以快速定位',
  descLocales: {
    en: 'Anchor navigation lists the sections on the current page and lets users jump to them quickly.',
  },
  components: {
    HScrollbar,
  },
  props: useAnchorProps,
  emits: useAnchorEmits,
  slots: useAnchorSlots,
  exposes: useAnchorExposes,
  setup(
    props,
    { slots, emit, expose }: HorizonWebSetupContext<AnchorEmits, AnchorSlots, AnchorExposes>,
  ) {
    const classHelper = new ComponentClassBlock('anchor');
    const { size } = toRefs(props);

    // global size
    const sizeRef = useSize(size, 'medium');

    const links = ref<string[]>([]);
    const activeLink = ref<string>('');
    const anchorRef = ref<HTMLElement | null>(null);
    const isScrolling = ref(false);

    const highLightLineStyle = ref<CSSProperties>(highLightLineDefaultStyle);

    const anchorClassClac = computed(() => cls(classHelper.block, classHelper.m(sizeRef.value)));
    const anchorStyleClac = computed(() => ({ ...props.style, maxHeight: `${props.maxHeight}px` }));

    const scrollContainer = ref<Window | HTMLElement | null>(null);
    let scrollController: AnchorScrollController | undefined;

    function updateScrollContainer() {
      scrollContainer.value = resolveAnchorScrollTarget(props.scrollContainer, document, selector =>
        console.warn(
          `[Horizon Web] Anchor scroll container "${selector}" was not found; using window instead.`,
        ),
      );
    }

    const getTarDomByLink = (link: string) => {
      return resolveAnchorHashTarget(link, document);
    };

    const scrollToHandle = (link: string) => {
      const tarDom = getTarDomByLink(link);
      if (!tarDom) {
        return;
      }
      const target = scrollContainer.value ?? window;
      const offsetTop = getAnchorOffsetTop(tarDom, target);
      const scrollTop = getAnchorScrollTop(target);
      const scrollOffset = getAnchorCustomOffset(props.scrollOffset, tarDom, target);
      const resDis = offsetTop + scrollTop - scrollOffset;

      isScrolling.value = true;
      scrollController?.scrollTo(resDis, props.scrollBehavior, () => {
        isScrolling.value = false;
      });
    };

    const updateHighlightLine = (link: string) => {
      if (!link) {
        highLightLineStyle.value = highLightLineDefaultStyle;
        return;
      }
      const activeLink = anchorRef.value?.querySelector(`[href='${link}']`)?.parentElement;
      if (!activeLink) {
        return;
      }
      const { offsetTop, clientHeight } = activeLink;

      highLightLineStyle.value = {
        top: `${offsetTop}px`,
        height: `${clientHeight}px`,
      };
    };

    const updateActiveLink = (link: string, needScroll = true) => {
      const prevLink = activeLink.value;
      activeLink.value = link;
      if (prevLink !== link) {
        emit('change', link, prevLink);
      }
      updateHighlightLine(link);
      needScroll && scrollToHandle(link);
    };

    const scrollHandle = () => {
      if (isScrolling.value) {
        return;
      }
      const target = scrollContainer.value ?? window;
      const sections: { top: number; link: string }[] = [];
      links.value.forEach(link => {
        const tarDom = getTarDomByLink(link);
        if (tarDom) sections.push({ link, top: getAnchorOffsetTop(tarDom, target) });
      });
      const firstTarget = sections.length ? getTarDomByLink(sections[0].link) : null;
      const boundsOffset = firstTarget
        ? getAnchorCustomOffset(props.boundsOffset, firstTarget, target)
        : typeof props.boundsOffset === 'number'
          ? props.boundsOffset
          : 0;
      updateActiveLink(resolveActiveAnchorLink(sections, boundsOffset), false);
    };

    const sharedProps = computed(() => ({
      size: sizeRef.value,
      showTitleSuffix: props.showTitleSuffix,
      placement: props.placement,
    }));
    const addLink = (link: string) => {
      if (!sharpLinkRegx.test(link) || links.value.includes(link)) {
        return;
      }
      links.value.push(link);
    };
    const removeLink = (link: string) => {
      links.value = links.value.filter(it => it !== link);
    };
    const clickLinkHandle = (linkInfo: { href: string; title: string }, e: MouseEvent) => {
      if (!props.changeHash) {
        e.preventDefault();
      }
      emit('click', linkInfo, e);
      updateActiveLink(linkInfo.href);
    };

    provide(AnchorContextInjectedKey, {
      sharedProps,
      activeLink,
      addLink,
      removeLink,
      clickLinkHandle,
      updateHighlightLine,
    });

    provide(AnchorPropsInjectedKey, props);

    // 动态监听变化，重新设置监听

    let prevScrollContainer: null | HTMLElement | Window = null;

    watch(
      scrollContainer,
      () => {
        setEventListener();
      },
      {
        immediate: true,
      },
    );

    function setEventListener() {
      removeEventListener();
      scrollContainer.value?.addEventListener('scroll', scrollHandle);
      prevScrollContainer = scrollContainer.value;
      if (scrollContainer.value)
        scrollController = createAnchorScrollController(scrollContainer.value);
    }

    function removeEventListener() {
      if (prevScrollContainer) {
        prevScrollContainer?.removeEventListener('scroll', scrollHandle);
      }
      scrollController?.destroy();
      scrollController = undefined;
    }

    watch(sizeRef, () => {
      void nextTick(() => updateHighlightLine(activeLink.value));
    });

    const anchorList = ref<AnchorListItem[]>();
    const getAnchorList = () => {
      const containerDom =
        scrollContainer.value instanceof HTMLElement
          ? scrollContainer.value
          : document.documentElement;
      return scanAnchorHeadings(containerDom, props.autoRenderRules);
    };

    const renderLinks = (list?: AnchorListItem[]) => {
      if (!list) {
        return null;
      }
      return list?.map(item => {
        return (
          <AnchorLink href={item.id && `#${item.id}`} title={item.title} key={item.id}>
            {renderLinks(item.children)}
          </AnchorLink>
        );
      });
    };

    function refreshAnchorList() {
      anchorList.value = getAnchorList();
    }

    const isCollapsed = ref(props.collapse);
    watch(
      () => props.collapse,
      value => (isCollapsed.value = value),
    );
    const showWrap = computed(() => (props.useCollapse ? !isCollapsed.value : true));
    const collapseBtnHandle = () => {
      const tarStatus = !isCollapsed.value;
      isCollapsed.value = tarStatus;
      emit('update:collapse', tarStatus);
    };
    const tooltipContent = computed(() =>
      typeof props.collapseText === 'string' ? props.collapseText : '',
    );
    const tooltipDisabled = computed(() => tooltipContent.value === '');

    onMounted(() => {
      nextTick(() => {
        updateScrollContainer();
        location.hash && updateActiveLink(decodeURI(location.hash));
        setEventListener();
        props.autoRender && refreshAnchorList();
      });
    });

    onBeforeUnmount(() => {
      removeEventListener();
    });

    watch(() => props.scrollContainer, updateScrollContainer, { flush: 'post' });

    expose({
      updateActiveLink,
      refreshAnchorList,
      updateScrollContainer,
      getAnchorList,
    });

    return () => (
      <div class={anchorClassClac.value} ref={anchorRef} style={anchorStyleClac.value}>
        {props.useCollapse && (
          <button
            type="button"
            aria-expanded={!isCollapsed.value}
            class={cls(
              classHelper.e('collapse-btn'),
              classHelper.is('collapse', isCollapsed.value),
            )}
            onClick={collapseBtnHandle}
          >
            <AIcon name={isCollapsed.value ? 'toggle_left' : 'toggle_right'} size={12} />
            <HTooltip
              content={tooltipContent.value}
              disabled={tooltipDisabled.value}
              placement="bottom"
              size="small"
              overflow
            >
              <span class={classHelper.e('collapse-btn-txt')}>
                {props.collapseText ?? useLocaleLang('anchor.navigator').value}
              </span>
            </HTooltip>
          </button>
        )}
        <HScrollbar size="small" maxHeight={props.maxHeight}>
          <div class={classHelper.e('wrap')} v-show={showWrap.value}>
            <div v-show={props.showLine} class={`${classHelper.e('line')}`}>
              <div
                v-show={props.showHighlightLine}
                class={`${classHelper.e('line--highlight')}`}
                style={highLightLineStyle.value}
              />
            </div>
            {props.autoRender ? renderLinks(anchorList.value) : slots?.default?.()}
          </div>
        </HScrollbar>
      </div>
    );
  },
});
