// packages/docs/demos/directives/v-popconfirm/demos/type.vue
<template>
  <n-button
    v-for="typeName in types"
    :key="typeName"
    v-popconfirm="{ type: typeName }"
    class="mr-2"
    @click="del"
  >
    {{ typeName }}
  </n-button>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { $message } from '@aurora/horizon-web';
export default defineComponent({
  setup() {
    const types = ['none', 'info', 'success', 'warning', 'error'];
    return {
      types,
      del: () => {
        $message('Action!');
      },
    };
  },
});
</script>

// packages/docs/demos/react/components/Tag/type.tsx
import { Space, Tag, type TagVariant } from '@aurora/horizon-react';

const variants: readonly TagVariant[] = ['', 'success', 'info', 'warning', 'error'];

export default function Demo() {
  return (
    <Space wrap>
      {variants.map(variant => (
        <Tag key={variant || 'default'} variant={variant}>
          {variant || 'default'}
        </Tag>
      ))}
    </Space>
  );
}
