// packages/horizon-web-react/src/components/Rate/index.tsx
import type {
  CSSProperties,
  FocusEvent,
  HTMLAttributes,
  KeyboardEvent,
  MouseEvent,
  ReactElement,
  ReactNode,
} from 'react';
import { forwardRef, useImperativeHandle, useMemo, useRef, useState } from 'react';
import type {
  RateCommandMap,
  RateCommonProps,
  RateEventMap,
  RateIconRegionContext,
  RateRegionMap,
} from '@aurora/core';
import {
  getRateItemStatus,
  getRateKeyboardValue,
  normalizeRateValue,
  RATE_DEFAULTS,
  resolveRateTooltip,
} from '@aurora/core';
import { cls, ComponentClassBlock } from '@aurora/theme';
import { useHorizonWebConfig } from '../../provider';
import type { ReactEventHandler, ReactRegionContent } from '../_shared/api';

export type RateHandle = RateCommandMap;

export interface RateProps
  extends
    RateCommonProps,
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'defaultValue' | 'onBlur' | 'onChange'> {
  /** 自定义评分图标。@en Custom rating icon or renderer. */
  renderIcon?: ReactRegionContent<RateRegionMap, 'icon'>;
  /** 值变化回调。@en Called when the rating changes. */
  onChange?: ReactEventHandler<RateEventMap, 'change'>;
  /** 原生失焦回调。@en Native blur callback. */
  onBlur?: ReactEventHandler<RateEventMap<FocusEvent<HTMLDivElement>>, 'blur'>;
  /** 无障碍名称。@en Accessible label for the rating control. */
  'aria-label'?: string;
}

const presetSize = { small: 12, medium: 16, large: 20 } as const;

export const Rate = forwardRef<RateHandle, RateProps>(function Rate(
  {
    value,
    defaultValue = RATE_DEFAULTS.defaultValue,
    count = RATE_DEFAULTS.count,
    half = RATE_DEFAULTS.half,
    showTooltip = RATE_DEFAULTS.showTooltip,
    tooltip = RATE_DEFAULTS.tooltip,
    readOnly = RATE_DEFAULTS.readOnly,
    disabled = RATE_DEFAULTS.disabled,
    size = 'medium',
    color,
    voidColor,
    disabledColor,
    gutter = RATE_DEFAULTS.gutter,
    renderIcon,
    onChange,
    onBlur,
    className,
    onKeyDown,
    ...nativeProps
  },
  ref,
): ReactElement {
  const config = useHorizonWebConfig();
  const namespace = config.namespace.toLowerCase();
  const classes = useMemo(() => new ComponentClassBlock('rate', namespace), [namespace]);
  const rootRef = useRef<HTMLDivElement>(null);
  const [uncontrolledValue, setUncontrolledValue] = useState(() =>
    normalizeRateValue(defaultValue, count, half),
  );
  const currentValue = normalizeRateValue(value ?? uncontrolledValue, count, half);
  const iconSize = typeof size === 'number' ? size : presetSize[size];
  const activeColor = color ?? `rgb(var(--${namespace}-rate-color-content))`;
  const emptyColor = voidColor ?? `var(--${namespace}-border-default)`;
  const inactiveColor = disabledColor ?? `var(--${namespace}-text-disabled)`;

  useImperativeHandle(ref, () => ({ focus: () => rootRef.current?.focus() }), []);

  function updateValue(nextValue: number): void {
    if (disabled || readOnly) return;
    const normalized = normalizeRateValue(nextValue, count, half);
    if (normalized === currentValue) return;
    if (value === undefined) setUncontrolledValue(normalized);
    onChange?.(normalized);
  }

  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>): void {
    onKeyDown?.(event);
    if (event.defaultPrevented || disabled || readOnly) return;
    const nextValue = getRateKeyboardValue(currentValue, event.key, count, half);
    if (nextValue === undefined) return;
    event.preventDefault();
    updateValue(nextValue);
  }

  function iconContent(context: RateIconRegionContext): ReactNode {
    return typeof renderIcon === 'function' ? renderIcon(context) : (renderIcon ?? '★');
  }

  return (
    <div
      {...nativeProps}
      aria-disabled={disabled}
      aria-readonly={readOnly}
      aria-valuemax={count}
      aria-valuemin={0}
      aria-valuenow={currentValue}
      className={cls(
        classes.block,
        classes.m('enabled', !readOnly && !disabled),
        classes.m('disabled', disabled),
        className,
      )}
      onBlur={onBlur}
      onKeyDown={handleKeyDown}
      ref={rootRef}
      role="slider"
      tabIndex={disabled ? -1 : 0}
    >
      {Array.from({ length: count }, (_, index) => {
        const itemIndex = index + 1;
        const status = getRateItemStatus(currentValue, itemIndex);
        const itemColor = disabled ? inactiveColor : status === 'void' ? emptyColor : activeColor;
        const style: CSSProperties = {
          color: itemColor,
          fontSize: iconSize,
          height: iconSize,
          marginRight: gutter,
          width: iconSize,
        };
        const context = { index, status, value: currentValue } satisfies RateIconRegionContext;
        const handleClick = (event: MouseEvent<HTMLSpanElement>): void => {
          const useHalf =
            half &&
            event.nativeEvent.offsetX < event.currentTarget.getBoundingClientRect().width / 2;
          updateValue(itemIndex - (useHalf ? 0.5 : 0));
        };
        return (
          <span
            aria-hidden="true"
            className={cls(
              classes.e('icon'),
              status === 'void' ? classes.m('void') : classes.m('full'),
            )}
            key={itemIndex}
            onClick={handleClick}
            style={style}
          >
            {iconContent(context)}
            {status === 'half' ? (
              <span
                className={classes.m('half')}
                style={{
                  color: activeColor,
                  left: 0,
                  overflow: 'hidden',
                  position: 'absolute',
                  top: 0,
                  width: '50%',
                }}
              >
                {iconContent(context)}
              </span>
            ) : null}
          </span>
        );
      })}
      {showTooltip ? (
        <span className={classes.e('tooltip')}>
          {resolveRateTooltip(currentValue, count, tooltip)}
        </span>
      ) : null}
    </div>
  );
});

export const HRate = Rate;
export type { RateItemStatus, RatePresetSize, RateSize, RateTooltip } from '@aurora/core';

// packages/horizon-web-vue/src/components/Rate/src/Rate.tsx
import type { ComputedRef, CSSProperties } from 'vue';
import { computed, defineComponent, inject, nextTick, ref, toRefs } from 'vue';
import type { RateItemStatus } from '@aurora/core';
import {
  getRateItemStatus,
  getRateKeyboardValue,
  normalizeRateValue,
  resolveRateTooltip,
} from '@aurora/core';
import { useRateProps } from './composables/useProps';
import type { RateEmits } from './composables/useEmits';
import type { HorizonWebSetupContext } from '@aurora/utils';
import { useRateEmits } from './composables/useEmits';
import { ComponentClassBlock, useNamespace } from '@aurora/utils';
import { AIcon } from '@aurora/icon';
import { GlobalSizeInjectedKey } from '~/components/Application/src/utils/injectedKeys';
import type { HApplicationSizeType } from '~/components/Application/src/composables/useProps';
import {
  HFormDisabledInjectedKey,
  HFormItemTriggerInjectedKey,
} from '~/components/Form/src/utils/injectedKeys';
import type { RateSlots } from './composables/useSlots';
import { useRateSlots } from './composables/useSlots';
import type { RateExposes } from './composables/useExposes';
import { useRateExposes } from './composables/useExposes';

export default defineComponent({
  name: `${useNamespace()}Rate`,
  desc: '用于评分操作',
  descLocales: { en: 'Use `v-model` to bind the current rating value.' },
  components: {
    AIcon,
  },
  props: useRateProps,
  emits: useRateEmits,
  slots: useRateSlots,
  exposes: useRateExposes,
  setup(props, { emit, slots, expose }: HorizonWebSetupContext<RateEmits, RateSlots, RateExposes>) {
    const classHelper = new ComponentClassBlock('rate');
    const iconSizeMap = {
      small: 12,
      medium: 16,
      large: 20,
    };

    const {
      count: countRef,
      showTooltip: showTooltipRef,
      tooltip: tooltipRef,
      disabled: disabledRef,
      readonly: readonlyRef,
      icon: iconRef,
      color: colorRef,
      voidColor: voidColorRef,
      disabledColor: disabledColorRef,
      modelValue: modelValueRef,
      gutter: gutterRef,
      half: halfRef,
    } = toRefs(props);
    const rootRef = ref<HTMLElement>();

    // global size
    const globalSize = inject(GlobalSizeInjectedKey, ref('medium'));
    const sizeRef = computed(() => props.size || globalSize.value) as ComputedRef<
      HApplicationSizeType | number
    >;

    /** formItemTrigger **/
    const formItemTrigger = inject(HFormItemTriggerInjectedKey, undefined);

    // form disabled inject
    const formDisabled = inject(HFormDisabledInjectedKey, undefined);
    const isDisabled = computed(() => formDisabled?.value || disabledRef.value);
    const currentValue = computed(() =>
      normalizeRateValue(modelValueRef.value, countRef.value, halfRef.value),
    );

    const iconList = computed(() => {
      return Array(+countRef.value)
        .fill(undefined)
        .map((_, index) => getRateItemStatus(currentValue.value, index + 1));
    });
    const renderIcons = (status: RateItemStatus, index: number) => {
      let trueScore = index + 1;
      const isFull = status === 'full';
      const isHalf = status === 'half';
      const sizeNumber: number =
        typeof sizeRef.value === 'number' ? sizeRef.value : iconSizeMap[sizeRef.value];
      const style = {
        width: sizeNumber,
        height: sizeNumber,
        marginRight: `${gutterRef.value}px`,
      };
      const shouldIconHalf = (event: MouseEvent) => {
        const centerLine = Object.hasOwn(iconSizeMap, sizeRef.value)
          ? iconSizeMap[sizeRef.value as keyof typeof iconSizeMap] / 2
          : parseInt(`${sizeRef.value}`, 10) / 2;

        return event.offsetX < centerLine;
      };
      const onChange = (event: MouseEvent) => {
        const shouldHalf = halfRef.value ? shouldIconHalf(event) : false;
        if (isDisabled.value || readonlyRef.value) {
          return;
        }
        if (shouldHalf) {
          trueScore -= 0.5;
        }
        emit('update:modelValue', trueScore);
        emit('change', trueScore);
        nextTick().then(() => {
          formItemTrigger?.('change');
        });
      };

      const getColor: string = isFull
        ? isDisabled.value
          ? disabledColorRef.value
          : colorRef.value
        : voidColorRef.value;

      const getSize = Object.hasOwn(iconSizeMap, sizeRef.value)
        ? iconSizeMap[sizeRef.value as keyof typeof iconSizeMap]
        : sizeRef.value;

      const getClass = [
        classHelper.e('icon'),
        isFull ? classHelper.m('full') : classHelper.m('void'),
      ];
      const getHalfStyle: CSSProperties = {
        position: 'absolute',
        overflow: 'hidden',
        top: 0,
        left: 0,
        width: '50%',
      };

      return slots.default ? (
        <span
          style={{
            fontSize: `${getSize}px`,
            color: getColor,
            ...style,
          }}
          class={getClass}
          onClick={onChange}
        >
          {slots.default?.({ index, status, value: currentValue.value })}
          {isHalf && (
            <span
              style={{
                ...getHalfStyle,
                color: colorRef.value,
              }}
            >
              {slots.default?.({ index, status, value: currentValue.value })}
            </span>
          )}
        </span>
      ) : (
        <span
          style={{
            fontSize: `${getSize}px`,
            color: getColor,
            ...style,
          }}
          class={getClass}
          onClick={onChange}
        >
          <AIcon name={iconRef.value} size={getSize} color={getColor} />
          {isHalf && (
            <AIcon
              style={{
                ...getHalfStyle,
              }}
              class={classHelper.m('half')}
              name={iconRef.value}
              size={getSize}
              color={colorRef.value}
            />
          )}
        </span>
      );
    };

    function onBlur(evt: FocusEvent) {
      emit('blur', evt);
      nextTick().then(() => {
        formItemTrigger?.('blur');
      });
    }

    function onKeydown(evt: KeyboardEvent) {
      if (readonlyRef.value || isDisabled.value) return;
      const value = getRateKeyboardValue(
        currentValue.value,
        evt.key,
        countRef.value,
        halfRef.value,
      );
      if (value === undefined) return;
      evt.preventDefault();
      emit('update:modelValue', value);
      emit('change', value);
      nextTick().then(() => formItemTrigger?.('change'));
    }

    expose({ focus: () => rootRef.value?.focus() });

    return () => (
      <div
        ref={rootRef}
        class={[
          classHelper.block,
          classHelper.m('enabled', !readonlyRef.value && !isDisabled.value),
          classHelper.m('disabled', isDisabled.value),
        ]}
        role="slider"
        aria-valuemin={0}
        aria-valuemax={countRef.value}
        aria-valuenow={currentValue.value}
        aria-disabled={isDisabled.value}
        aria-readonly={readonlyRef.value}
        tabindex={isDisabled.value ? -1 : 0}
        onKeydown={onKeydown}
        onBlur={onBlur}
      >
        {iconList.value.map((status, index) => {
          return renderIcons(status, index);
        })}
        {showTooltipRef.value && (
          <span class={classHelper.e('tooltip')}>
            {resolveRateTooltip(currentValue.value, countRef.value, tooltipRef.value)}
          </span>
        )}
      </div>
    );
  },
});
