// packages/horizon-web-react/src/components/Typography/index.tsx
import type { ElementType, HTMLAttributes, ReactElement, ReactNode } from 'react';
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import type {
  TypographyCommandMap,
  TypographyCommonProps,
  TypographyEventMap,
  TypographyRegionMap,
} from '@aurora/core';
import {
  resolveTypographyEllipsisLines,
  resolveTypographyTag,
  TYPOGRAPHY_DEFAULTS,
} from '@aurora/core';
import { cls, ComponentClassBlock } from '@aurora/theme';
import { useHorizonWebConfig } from '../../provider';
import { Button } from '../Button';
import type { ReactEventHandler, ReactRegionContent } from '../_shared/api';

export type TypographyHandle = TypographyCommandMap;

export interface TypographyProps
  extends
    TypographyCommonProps,
    Omit<
      HTMLAttributes<HTMLElement>,
      'children' | 'defaultValue' | 'onChange' | 'onCopy' | 'prefix'
    > {
  /** 文本内容。@en Text content. */
  children?: ReactRegionContent<TypographyRegionMap, 'content'>;
  /** 前置内容。@en Leading content. */
  prefix?: ReactRegionContent<TypographyRegionMap, 'prefix'>;
  /** 后置内容。@en Trailing content. */
  suffix?: ReactRegionContent<TypographyRegionMap, 'suffix'>;
  /** 文本值变化回调。@en Called when the text value changes. */
  onValueChange?: ReactEventHandler<TypographyEventMap, 'valueChange'>;
  /** 编辑提交回调。@en Called when editing is committed. */
  onChange?: ReactEventHandler<TypographyEventMap, 'change'>;
  /** 复制完成回调。@en Called after a copy attempt. */
  onCopy?: ReactEventHandler<TypographyEventMap, 'copy'>;
}

export const Typography = forwardRef<TypographyHandle, TypographyProps>(function Typography(
  {
    value,
    defaultValue = TYPOGRAPHY_DEFAULTS.defaultValue,
    tag = TYPOGRAPHY_DEFAULTS.tag,
    level,
    variant = TYPOGRAPHY_DEFAULTS.variant,
    size = TYPOGRAPHY_DEFAULTS.size,
    weight = TYPOGRAPHY_DEFAULTS.weight,
    block = TYPOGRAPHY_DEFAULTS.block,
    italic = TYPOGRAPHY_DEFAULTS.italic,
    underline = TYPOGRAPHY_DEFAULTS.underline,
    deleted = TYPOGRAPHY_DEFAULTS.deleted,
    code = TYPOGRAPHY_DEFAULTS.code,
    ellipsis = TYPOGRAPHY_DEFAULTS.ellipsis,
    copyable = TYPOGRAPHY_DEFAULTS.copyable,
    editable = TYPOGRAPHY_DEFAULTS.editable,
    disabled = TYPOGRAPHY_DEFAULTS.disabled,
    prefix,
    suffix,
    onValueChange,
    onChange,
    onCopy,
    children,
    className,
    style,
    ...nativeProps
  },
  ref,
): ReactElement {
  const config = useHorizonWebConfig();
  const classes = useMemo(
    () => new ComponentClassBlock('typography', config.namespace.toLowerCase()),
    [config.namespace],
  );
  const [internalValue, setInternalValue] = useState(defaultValue);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(value ?? defaultValue);
  const inputRef = useRef<HTMLInputElement>(null);
  const contentRef = useRef<HTMLSpanElement>(null);
  const controlled = value !== undefined;
  const textValue = controlled ? value : internalValue;

  useEffect(() => {
    if (controlled && !editing) setDraft(value);
  }, [controlled, editing, value]);

  function currentText(): string {
    if (controlled || internalValue !== '') return textValue;
    return contentRef.current?.textContent ?? '';
  }

  function edit(): void {
    if (!editable || disabled) return;
    setDraft(currentText());
    setEditing(true);
    queueMicrotask(() => inputRef.current?.focus());
  }

  function cancelEdit(): void {
    setDraft(currentText());
    setEditing(false);
  }

  function commitEdit(): void {
    if (!editing) return;
    if (!controlled) setInternalValue(draft);
    setEditing(false);
    onValueChange?.(draft);
    onChange?.(draft);
  }

  async function copy(): Promise<boolean> {
    if (disabled) return false;
    const copiedValue = currentText();
    let success = false;
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(copiedValue);
        success = true;
      } else {
        const textarea = document.createElement('textarea');
        textarea.value = copiedValue;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.append(textarea);
        textarea.select();
        success = document.execCommand('copy');
        textarea.remove();
      }
    } catch {
      success = false;
    }
    onCopy?.(copiedValue, success);
    return success;
  }

  useImperativeHandle(ref, () => ({ edit, cancelEdit, copy }));

  if (editing) {
    return (
      <input
        aria-label="Edit text"
        className={classes.e('editor')}
        onBlur={commitEdit}
        onInput={event => setDraft(event.currentTarget.value)}
        onKeyDown={event => {
          if (event.key === 'Enter' && !event.nativeEvent.isComposing) commitEdit();
          if (event.key === 'Escape') cancelEdit();
        }}
        ref={inputRef}
        value={draft}
      />
    );
  }

  const Root = resolveTypographyTag(tag, level) as ElementType;
  const lines = resolveTypographyEllipsisLines(ellipsis);
  const renderedContent: ReactNode = controlled || internalValue !== '' ? textValue : children;
  return (
    <Root
      {...nativeProps}
      className={cls(
        classes.block,
        classes.m(variant),
        classes.m(size),
        classes.m(weight),
        classes.m(`heading-${level}`, level !== undefined),
        classes.is('block', block || level !== undefined),
        classes.is('italic', italic),
        classes.is('underline', underline),
        classes.is('deleted', deleted),
        classes.is('code', code),
        classes.is('ellipsis', lines > 0),
        classes.is('disabled', disabled),
        className,
      )}
      style={{
        ...(style ?? {}),
        ...(lines > 1 ? { WebkitLineClamp: lines, '--h-typography-size-lines': lines } : {}),
      }}
    >
      {prefix}
      <span className={classes.e('content')} ref={contentRef}>
        {renderedContent}
      </span>
      {suffix}
      {copyable || editable ? (
        <span className={classes.e('actions')}>
          {copyable ? (
            <Button
              aria-label="Copy"
              disabled={disabled}
              link
              onClick={() => void copy()}
              size="small"
              variant="normal"
            >
              Copy
            </Button>
          ) : null}
          {editable ? (
            <Button
              aria-label="Edit"
              disabled={disabled}
              link
              onClick={edit}
              size="small"
              variant="normal"
            >
              Edit
            </Button>
          ) : null}
        </span>
      ) : null}
    </Root>
  );
});

export const HTypography = Typography;
export type {
  TypographyEllipsis,
  TypographyLevel,
  TypographySize,
  TypographyVariant,
  TypographyWeight,
} from '@aurora/core';

// packages/horizon-web/src/components/Typography/src/Typography.tsx
import type { HorizonWebSetupContext } from '@aurora/utils';
import { ComponentClassBlock, useNamespace } from '@aurora/utils';
import { computed, defineComponent, nextTick, ref, watch } from 'vue';
import HButton from '~/components/Button/src/Button';
import HInput from '~/components/Input/src/Input';
import useLocaleLang from '~/utils/useLocaleLang';
import type { TypographyEmits } from './composables/useEmits';
import { useTypographyEmits } from './composables/useEmits';
import type { TypographyExposes } from './composables/useExposes';
import { useTypographyExposes } from './composables/useExposes';
import { useTypographyProps } from './composables/useProps';
import type { TypographySlots } from './composables/useSlots';
import { useTypographySlots } from './composables/useSlots';

export default defineComponent({
  name: `${useNamespace()}Typography`,
  desc: '统一展示标题、正文和辅助文本，并提供省略、复制与编辑能力',
  descLocales: { en: 'Displays semantic text with ellipsis, copy, and edit actions.' },
  inheritAttrs: false,
  props: useTypographyProps,
  emits: useTypographyEmits,
  slots: useTypographySlots,
  exposes: useTypographyExposes,
  setup(
    props,
    {
      attrs,
      slots,
      emit,
      expose,
    }: HorizonWebSetupContext<TypographyEmits, TypographySlots, TypographyExposes>,
  ) {
    const classHelper = new ComponentClassBlock('typography');
    const editing = ref(false);
    const draft = ref(props.modelValue ?? '');
    const inputRef = ref<any>();
    const contentRef = ref<HTMLElement>();
    const copyText = useLocaleLang('typography.copy', 'Copy');
    const editText = useLocaleLang('typography.edit', 'Edit');

    watch(
      () => props.modelValue,
      value => {
        if (!editing.value) draft.value = value ?? '';
      },
    );

    const rootTag = computed(() => (props.level ? `h${props.level}` : props.tag));
    const ellipsisLines = computed(() =>
      props.ellipsis === true ? 1 : typeof props.ellipsis === 'number' ? props.ellipsis : 0,
    );
    const getContent = () => props.modelValue ?? contentRef.value?.textContent ?? '';

    const edit = () => {
      if (!props.editable || props.disabled) return;
      draft.value = props.modelValue ?? '';
      editing.value = true;
      nextTick(() => inputRef.value?.focus?.());
    };

    const cancelEdit = () => {
      draft.value = props.modelValue ?? '';
      editing.value = false;
    };

    const commitEdit = () => {
      if (!editing.value) return;
      editing.value = false;
      emit('update:modelValue', draft.value);
      emit('change', draft.value);
    };

    const copy = async () => {
      if (props.disabled) return false;
      const value = getContent();
      let success = false;
      try {
        if (navigator.clipboard?.writeText) {
          await navigator.clipboard.writeText(value);
          success = true;
        } else if (typeof document !== 'undefined') {
          const textarea = document.createElement('textarea');
          textarea.value = value;
          textarea.style.position = 'fixed';
          textarea.style.opacity = '0';
          document.body.appendChild(textarea);
          textarea.select();
          success = document.execCommand('copy');
          document.body.removeChild(textarea);
        }
      } catch {
        success = false;
      }
      emit('copy', value, success);
      return success;
    };

    expose({ edit, cancelEdit, copy });

    return () => {
      const RootTag = rootTag.value as any;
      const lines = ellipsisLines.value;
      const classes = [
        classHelper.block,
        classHelper.m(props.type),
        classHelper.m(props.size),
        classHelper.m(props.weight),
        classHelper.m(`heading-${props.level}`, !!props.level),
        classHelper.is('block', props.block || !!props.level),
        classHelper.is('italic', props.italic),
        classHelper.is('underline', props.underline),
        classHelper.is('deleted', props.deleted),
        classHelper.is('code', props.code),
        classHelper.is('ellipsis', lines > 0),
        classHelper.is('disabled', props.disabled),
      ];

      if (editing.value) {
        return (
          <HInput
            ref={inputRef}
            class={classHelper.e('editor')}
            modelValue={draft.value}
            aria-label={editText.value as string}
            onUpdate:modelValue={(value: string) => (draft.value = value)}
            onBlur={commitEdit}
            onKeydown={(event: KeyboardEvent) => {
              if (event.key === 'Enter' && !event.isComposing) commitEdit();
              if (event.key === 'Escape') cancelEdit();
            }}
          />
        );
      }

      return (
        <RootTag
          {...attrs}
          class={[classes, attrs.class]}
          style={[
            lines > 1 ? { WebkitLineClamp: lines, '--h-typography-lines': lines } : undefined,
            attrs.style,
          ]}
        >
          {slots.prefix?.()}
          <span ref={contentRef} class={classHelper.e('content')}>
            {props.modelValue !== undefined ? props.modelValue : slots.default?.()}
          </span>
          {slots.suffix?.()}
          {(props.copyable || props.editable) && (
            <span class={classHelper.e('actions')}>
              {props.copyable && (
                <HButton
                  link
                  type="normal"
                  size="small"
                  icon="copy"
                  disabled={props.disabled}
                  aria-label={copyText.value as string}
                  onClick={copy}
                />
              )}
              {props.editable && (
                <HButton
                  link
                  type="normal"
                  size="small"
                  icon="edit"
                  disabled={props.disabled}
                  aria-label={editText.value as string}
                  onClick={edit}
                />
              )}
            </span>
          )}
        </RootTag>
      );
    };
  },
});
