// packages/locale-vue/src/components/DateLocale.tsx
import type { PropType } from 'vue';
import { defineComponent, getCurrentInstance } from 'vue';
import type { DateLocaleAvailableShownType } from '@aurora/locale';
import { useNamespace } from '@aurora/utils';

export default defineComponent({
  name: `${useNamespace()}DateLocale`,
  props: {
    value: {
      type: [String, Number, Date],
      required: true,
    },
    type: {
      type: String as PropType<DateLocaleAvailableShownType>,
      required: true,
    },
  },
  setup(props) {
    const { proxy } = getCurrentInstance()!;
    return () => <div class="horizon-web-date-locale">{proxy!.$root?.d(props.value, props.type)}</div>;
  },
});

// packages/locale-react/src/components/DateLocale.ts
import type { HTMLAttributes, ReactElement } from 'react';
import { createElement } from 'react';
import type { DateLocaleAvailableShownType } from '@aurora/locale';
import { useLocale } from '../context';
import { mergeClassName } from './utils';

export interface DateLocaleProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  value: string | number | Date;
  type: DateLocaleAvailableShownType;
}

export function DateLocale({ value, type, className, ...props }: DateLocaleProps): ReactElement {
  const locale = useLocale();
  return createElement(
    'span',
    { ...props, className: mergeClassName('horizon-web-date-locale', className) },
    locale.dateService.d(value, type),
  );
}
