// packages/locale-vue/src/components/LangLocale.tsx
import type { PropType } from 'vue';
import { defineComponent, getCurrentInstance } from 'vue';
import type { LocaleSupportLang } from '@aurora/locale';
import { useNamespace } from '@aurora/utils';

export default defineComponent({
  name: `${useNamespace()}LangLocale`,
  props: {
    value: {
      type: String,
      required: true,
    },
    lang: {
      type: String as PropType<LocaleSupportLang>,
    },
  },
  setup(props) {
    const { proxy } = getCurrentInstance()!;
    return () => (
      <div class="horizon-web-lang-locale">{proxy!.$root!.t(props.value, props.lang)}</div>
    );
  },
});

// packages/locale-react/src/components/LangLocale.ts
import type { HTMLAttributes, ReactElement } from 'react';
import { createElement } from 'react';
import type { LocaleSupportLang } from '@aurora/locale';
import { useLocale } from '../context';
import { mergeClassName } from './utils';

export interface LangLocaleProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  value: string;
  lang?: LocaleSupportLang;
}

export function LangLocale({ value, lang, className, ...props }: LangLocaleProps): ReactElement {
  const locale = useLocale();
  return createElement(
    'span',
    { ...props, className: mergeClassName('horizon-web-lang-locale', className) },
    locale.langService.t(value, lang),
  );
}
