// packages/docs/demos/react/components/Tag/type.tsx
import { Space, Tag, type TagVariant } from '@aurora/horizon-react';

const variants: readonly TagVariant[] = ['', 'success', 'info', 'warning', 'error'];

export default function Demo() {
  return (
    <Space wrap>
      {variants.map(variant => (
        <Tag key={variant || 'default'} variant={variant}>
          {variant || 'default'}
        </Tag>
      ))}
    </Space>
  );
}

// packages/docs/demos/components/Tag/demos/type.vue
<template>
  <h-row>
    <h-col>
      <h-tag :clickable="false">Default</h-tag>
      <h-tag :clickable="false" type="success">Success</h-tag>
      <h-tag :clickable="false" type="info">Info</h-tag>
      <h-tag :clickable="false" type="warning">Warning</h-tag>
      <h-tag :clickable="false" type="error">Error</h-tag>
    </h-col>
  </h-row>
</template>

<script setup lang="ts">
</script>

<style scoped>
</style>
